name: Build Debian Package
  
on:
  push:
    branches:
      - master
  workflow_dispatch:
  
env:
  PACKAGE_NAME: livepeer
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential debhelper fakeroot git devscripts
      - name: Set Git user info
        run: |
          git config --global user.email "GITHUB_ACTIONS@raf.sundara.tv"
          git config --global user.name "Sundara.eth"
      - name: Create changelog entry
        run: |
          export DEBEMAIL="GITHUB_ACTIONS@raf.sundara.tv"
          echo "Updating changelog for ${{ github.ref }} release."
          UPSTREAM_URL="https://github.com/livepeer/go-livepeer"
          LATEST_RELEASE=$(curl --silent "${UPSTREAM_URL}/releases/latest" | sed 's#.*tag/\(.*\)\".*#\1#')
           echo -e "\n\nlivepeer (${{ github.ref }}) unstable; urgency=medium\n\n* New upstream release. See ${UPSTREAM_URL}/releases/tag/${LATEST_RELEASE}.\n\n -- GITHUB ACTIONS BOT <ci@mydomain.com>  $(date -R)\n" > debian/changelog
          git add debian/changelog
          git commit -m "Update changelog for ${{ github.ref }} release"
          git push
      - name: Build Debian Package
        run: |
          dpkg-buildpackage -b -us -uc
      - name: Upload package to GitHub releases
        uses: actions/upload-release-asset@v1
        with:
          asset_path: |
            ../${PACKAGE_NAME}_*.deb
            ../${PACKAGE_NAME}_*.deb.asc
            ../${PACKAGE_NAME}_*.dsc
            ../${PACKAGE_NAME}_*.tar.xz
            ../${PACKAGE_NAME}_*.buildinfo
          name: ${{ env.PACKAGE_NAME }}_${{ github.ref }}_amd64.deb
          label: ${{ env.PACKAGE_NAME }}_${{ github.ref }}_amd64.deb
          mime_type: application/octet-stream
