name: Build Debian Package

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  PACKAGE_NAME: livepeer

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential debhelper fakeroot git
      - name: Create changelog entry
        run: |
          export DEBEMAIL="ci@raf.sundara.tv"
          export DEBFULLNAME="GITHUB ACTIONS BOT"
          git fetch --tags
          PREV_TAG=$(git describe --tags --abbrev=0)
          NEXT_TAG=$(echo $PREV_TAG | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          debchange --newversion $NEXT_TAG --distribution unstable "New upstream release."
      - name: Build Debian Package
        run: |
          dpkg-buildpackage -b -us -uc -aamd64
        env:
          DEB_BUILD_OPTIONS: "nocheck"
      - name: Upload package to GitHub releases
        uses: actions/upload-release-asset@v1
        with:
          asset_path: |
            ../${PACKAGE_NAME}_*.deb
            ../${PACKAGE_NAME}_*.deb.asc
            ../${PACKAGE_NAME}_*.dsc
            ../${PACKAGE_NAME}_*.tar.xz
            ../${PACKAGE_NAME}_*.buildinfo
          name: ${{ env.PACKAGE_NAME }}_${{ github.ref }}_amd64.deb
          label: ${{ env.PACKAGE_NAME }}_${{ github.ref }}_amd64.deb
          mime_type: application/octet-stream
