name: Release

on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential debhelper fakeroot git devscripts

      - name: Set up GPG key
        run: |
          gpg --import "${{ secrets.GPG_PRIVATE_KEY }}"
          echo "${{ secrets.GPG_PASSPHRASE }}" | gpg --batch --passphrase-fd 0 --pinentry-mode loopback --for-your-eyes-only --import-options import-show --import

      - name: Create changelog entry
        run: |
          export DEBEMAIL="ci@mydomain.com"
          echo "livepeer (${{ github.ref }}) unstable; urgency=medium" > debian/changelog
          echo -e "\n* New upstream release. See https://github.com/livepeer/go-livepeer/releases/tag/${{ github.ref }}.\n\n -- GITHUB ACTIONS BOT <ci@mydomain.com>  $(date -R)\n" >> debian/changelog

      - name: Build package
        run: |
          debuild -b -us -uc

      - name: Publish package
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body: "Release ${{ github.ref }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
