name: Debian Package

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-deb-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential debhelper dh-systemd devscripts fakeroot lintian
      - name: Build Debian package
        run: |
          dpkg-buildpackage -b -us -uc
      - name: Upload package to GitHub releases
        uses: actions/upload-release-asset@v1
        with:
          asset_path: |
            ../*.deb
            ../*.dsc
            ../*.tar.xz
            ../*.changes
          name: ${{ env.PACKAGE_NAME }}
          label: ${{ env.PACKAGE_NAME }}
          mime_type: application/octet-stream
        env:
          PACKAGE_NAME: livepeer
