name: Build Debian Package

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  PACKAGE_NAME: livepeer
  PACKAGE_VERSION: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Get release tag name
        id: get_tag
        uses: actions/github-script@v4
        with:
          script: |
            const resp = await github.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            console.log(resp.data.tag_name || context.ref.replace('refs/tags/', ''));
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential debhelper fakeroot
      - name: Build Debian Package
        run: |
          dpkg-buildpackage -b -us -uc
      - name: Upload package to GitHub releases
        uses: actions/upload-release-asset@v1
        with:
          asset_path: |
            ../${PACKAGE_NAME}_${PACKAGE_VERSION}_amd64.deb
            ../${PACKAGE_NAME}_${PACKAGE_VERSION}_amd64.deb.asc
            ../${PACKAGE_NAME}_${PACKAGE_VERSION}.dsc
            ../${PACKAGE_NAME}_${PACKAGE_VERSION}.tar.xz
            ../${PACKAGE_NAME}_${PACKAGE_VERSION}_amd64.buildinfo
          name: ${{ env.PACKAGE_NAME }}_${{ env.PACKAGE_VERSION }}_amd64.deb
          label: ${{ env.PACKAGE_NAME }}_${{ env.PACKAGE_VERSION }}_amd64.deb
          mime_type: application/octet-stream
