name: Build Debian Package

on:
  workflow_dispatch:
    push:
      tags:
        - '*'

env:
  PACKAGE_NAME: livepeer
  GITHUB_EMAIL: ci@mydomain.com
  GITHUB_USERNAME: GITHUB_ACTIONS

jobs:
  build:
    name: Build Debian Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential debhelper fakeroot git devscripts

      - name: Create changelog entry
        run: |
          echo "Updating changelog for ${{ github.ref }} release."
          echo -e "\n\n${PACKAGE_NAME} (${{ github.ref }}) unstable; urgency=medium\n\n* New upstream release. See ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/releases/tag/${{ github.ref }}.\n\n -- ${GITHUB_USERNAME} <${GITHUB_EMAIL}>  $(date -R)\n" > debian/changelog

      - name: Commit changelog
        run: |
          git add debian/changelog
          git config --global user.email "${GITHUB_EMAIL}"
          git config --global user.name "${GITHUB_USERNAME}"
          git commit -m "Update changelog for ${GITHUB_REF} release"

      - name: Build package
        run: |
          debuild -b -us -uc
