name: Debian Package

on:
  workflow_dispatch:
    inputs:
      livepeer_release_url:
        description: 'Livepeer Release URL'
        required: true

jobs:
  build_deb_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up GnuPG
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Install dependencies
        run: sudo apt-get install -y debhelper devscripts equivs

      - name: Download and verify livepeer-linux-amd64.tar.gz
        run: |
          wget "${{ github.event.inputs.livepeer_release_url }}/livepeer-linux-amd64.tar.gz"
          wget "${{ github.event.inputs.livepeer_release_url }}/livepeer-linux-amd64.tar.gz.sig"
          gpg --verify livepeer-linux-amd64.tar.gz.sig livepeer-linux-amd64.tar.gz

      - name: Build Debian package
        run: |
          # Build the Debian package here, assuming you have a "debian" directory in your repo containing necessary files
          dpkg-buildpackage -us -uc

      - name: Sign Debian package
        run: |
          debsigs --sign=origin -k $GPG_KEY_ID *.deb
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}

      - name: Check package size
        id: check_size
        run: |
          SIZE=$(stat -c %s *.deb)
          echo "::set-output name=size::$SIZE"
          if [ "$SIZE" -gt 199000000 ]; then
            echo "Package size exceeds 199 MB, aborting."
            exit 1
          fi

      - name: Upload Debian package
        if: steps.check_size.outputs.size <= 199000000
        uses: actions/upload-artifact@v2
        with:
          name: livepeer-deb
          path: ./*.deb
